# Generated by Django 6.1 on 2026-08-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('subject', models.CharField(choices=[('website-design', 'طراحی وب\u200cسایت'), ('web-app', 'توسعه وب\u200cاپلیکیشن'), ('ai-telegram-bot', 'هوش مصنوعی و ربات تلگرام'), ('ui-ux', 'طراحی رابط کاربری/تجربه کاربری'), ('support', 'پشتیبانی سایت'), ('other', 'سایر')], max_length=30, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
