# Generated by Django 6.1 on 2026-08-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('category', models.CharField(choices=[('Websites', 'Websites'), ('UI/UX Design', 'UI/UX Design'), ('AI  & Telegram bots', 'AI & Telegram bots'), ('Content Production', 'Content Production')], max_length=30, verbose_name='دسته\u200cبندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='تصویر')),
                ('href', models.URLField(blank=True, default='#', verbose_name='لینک پروژه')),
                ('swap_footer', models.BooleanField(default=False, verbose_name='جابه\u200cجایی فوتر (swapFooter)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
